from pydantic import BaseModel, validator
from typing import Optional
import uuid
from datetime import datetime

# Import the Enum from models to reuse it
from ..models.queue_entry import QueueEntryStatus
# from .user import User # To show user details if needed
# from .queue import Queue # To show queue details if needed

class QueueEntryBase(BaseModel):
    status: QueueEntryStatus = QueueEntryStatus.WAITING
    estimated_wait_time_at_join_minutes: Optional[int] = None
    priority_level: int = 0
    notes_by_user: Optional[str] = None

    @validator('estimated_wait_time_at_join_minutes', 'priority_level')
    def check_non_negative(cls, value):
        if value is not None and value < 0:
            raise ValueError('must be a non-negative integer or null')
        return value

class QueueEntryCreate(BaseModel): # User provides minimal info to join
    # queue_id is usually a path parameter
    # user_id is from authenticated user
    # ticket_number is generated by the system
    notes_by_user: Optional[str] = None
    priority_level: Optional[int] = 0 # Could be part of a premium feature

class QueueEntryUpdate(BaseModel): # For staff/system to update an entry
    status: Optional[QueueEntryStatus] = None
    notes_by_staff: Optional[str] = None
    # Other fields like called_at, service_start_time, served_at will be set by system logic

class QueueEntry(QueueEntryBase): # Schema for reading QueueEntry data
    id: uuid.UUID
    queue_id: uuid.UUID
    user_id: uuid.UUID
    ticket_number: int

    joined_at: datetime
    called_at: Optional[datetime] = None
    service_start_time: Optional[datetime] = None
    served_at: Optional[datetime] = None

    created_at: datetime # from model
    updated_at: datetime # from model

    # user: Optional[User] = None # To show full user details
    # queue: Optional[Queue] = None # To show full queue details

    class Config:
        from_attributes = True


# Forward reference resolution
from .user import UserBase # Using Base to avoid circular full model
from .queue import QueueBase # Using Base to avoid circular full model
QueueEntry.model_rebuild()
UserBase.model_rebuild()
QueueBase.model_rebuild()
